name: Feature Request
description: File a bug report
title: "[Feature Request]: "
labels: ["feature", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to request a new feature!
  - type: dropdown
    id: types
    attributes:
      label: What type of enhancement/feature is this?
      multiple: true
      options:
        - New UI Component
        - Visual Changes to existing UI Components
        - Behaviour Changes to existing UI Components
        - Documentation Improvements
        - Other
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case/Reasoning for feature
      description: Please provide a use case or reason for this feature.
      placeholder: When using component X it would be useful if ... because ...
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a description of the feature. If applicable, add screenshots to help explain your need.
      placeholder: A clear and concise description of what you want from this feature.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/innofake/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: 'I have [searched for existing issues](https://github.com/innofake/inno-random-joke/issues) and to the best of my knowledge this is not a duplicate'
          required: true
        - label: 'This is a single feature'
          required: true
